web/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post 'static_pages/create'
  resources :images
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web/app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :path, PictureUploader
end

web/app/models/target.rb
class Target < ApplicationRecord
  mount_uploader :path, TargetUploader
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

web/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
    @images.each do |i|
      if i.mean_h.nil?
        i.mean_h = -1
        i.mean_s = -1
        i.mean_v = -1
      end
    end
  end

  def new
    @image = Image.new
  end

  def create
    pa = image_params

    # バリデーション
    if pa[:path] == nil
      flash[:danger] = '画像が選択されていません。'
      redirect_to new_image_url
      return
    elsif Image.find_by_path(pa[:path].original_filename) != nil
      flash[:danger] = 'ファイル名が重複しています。'
      redirect_to new_image_url
      return
    end

    # アップロードされた画像を保存
    image = Image.new(pa)
    if image.save
      # Python プログラムを起動
      if Rails.env == 'production'
        system('python /home/okabi/Projects/mosaic/main_save.py ' + image.id.to_s)
      end
      flash[:success] = '画像のアップロードが完了しました。'
      redirect_to images_url
    else
      flash[:danger] = 'アップロード時にエラーが発生しました。もう一度アップロードしてください。'
      redirect_to new_image_url
    end
  end

  def edit
    @image = Image.find_by_id(params[:id])
    if @image.nil?
      redirect_to images_url
      return
    end
  end

  def update
    @image = Image.find_by_id(params[:id])
    pa = params.require(:image).permit(:fav_count)
    if !@image.nil?
      @image.update_attribute('fav_count', pa[:fav_count])
      flash[:success] = '更新が正常に完了しました。'
    end
    redirect_to images_url
  end

  def destroy
    @image = Image.find_by_id(params[:id])
    text = "#{@image.path} を削除しました。"
    if !@image.nil?
      @image.destroy
      flash[:success] = text
    end
    redirect_to images_url
  end

  private

  def image_params
    params.require(:image).permit(:fav_count, :path)
  end
end

web/app/controllers/static_pages_controller.rb
# coding: utf-8
require "open3"

class StaticPagesController < ApplicationController
  def home
    @target = Target.new
    @images_num = Image.all.size
    @log = []
    if Rails.env == 'production'
      File.open('/home/okabi/Projects/mosaic/web/public/log.txt', 'r') do |file|
        file.each do |s|
          @log.push(s)
        end
      end
    end
  end

  def create
    # バリデーション
    if params['target'] == nil
      flash[:danger] = '画像が選択されていません。'
      redirect_to root_url
      return
    elsif Image.all.size == 0
      flash[:danger] = '素材画像が登録されていません。メニューから登録してください。'
      redirect_to root_url
      return
    end
    pa = target_params

    # アップロードされた画像を保存してモザイクアート生成開始
    target = Target.new(pa)
    if target.save
      # Python プログラムを実行
      if Rails.env == 'production'
        Open3.popen3('python /home/okabi/Projects/mosaic/main.py ' + target.id.to_s + ' > /home/okabi/Projects/mosaic/web/public/log.txt 2>&1')
      end
      flash[:success] = 'モザイクアートを生成しています。しばらくしてからページを更新してください。'
      redirect_to root_url
    else
      flash[:danger] = 'アップロード時にエラーが発生しました。もう一度アップロードしてください。'
      redirect_to root_url
    end
  end

  private

  def target_params
    params.require(:target).permit(:path)
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
  # form_for の入力フィールド(file_field)となる HTML を返します。
  def form_file_field(form, attribute, label, size: 8, description: nil, example: nil, required: true)
    form_xxxx 'file_field', form, attribute, label, size: size, description: description, example: example, required: required
  end

  # form_for の入力フィールド(number_field)となる HTML を返します。
  def form_number_field(form, attribute, label, size: 8, description: nil, example: nil, required: true)
    form_xxxx 'number_field', form, attribute, label, size: size, description: description, example: example, required: required
  end

  # form_for の submit ボタンとなる HTML を返します。
  def form_submit(form, label, size: 8, type: 'btn-primary')
    "<div class='col-sm-offset-2 col-sm-#{size}'>".html_safe +
      (form.submit label, class: "form-control btn #{type}") +
    "</div>".html_safe
  end

  # Bootstrap の Panel となる HTML を返します。
  def panel(type: 'primary', header: nil, body: nil, footer: nil)
    "<div class='panel panel-#{type}'>".html_safe +
      (header ?
        "<div class='panel-heading'>#{header}</div>" : "").html_safe +
      (body ?
          "<div class='panel-body'>#{body}</div>" : "").html_safe +
      (footer ?
          "<div class='panel-footer'>#{footer}</div>" : "").html_safe +
    "</div>".html_safe
  end

  private

    # form_xxxx (form_text_field や form_text_area) で呼び出されるメソッドです。
    def form_xxxx(xxxx, form, attribute, label, size: 8, description: nil, example: nil, required: true)
      class_options = []
      class_options.push('validation') if required
      class_options.push('form-control') if xxxx != 'file_field'
      html_option = { class: class_options.join(' ') }
      if xxxx == 'number_field'
        html_option[:min] = 0
      elsif xxxx == 'file_field'
        html_option[:accept] = 'image/png,image/gif,image/jpeg'
      end
      "<div class='form-group'>".html_safe +
        form.label(attribute, label, class: 'col-sm-2 control-label') +
        "<div class='col-sm-#{size}'>".html_safe +
        form.send(xxxx, attribute, html_option) +
        (description ?
          "<span class='help-block'>#{description}</span>" : "").html_safe +
        (example ?
          "<span class='help-block'><span class='label label-default'>例</span>#{example}</span>" : "").html_safe +
        "</div>".html_safe +
      "</div>".html_safe
    end
end

web/app/helpers/images_helper.rb
module ImagesHelper
end

web/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

web/app/views/images/_form.html.erb
<%= form_for(image, url: form_for_url, html: { class: "form-horizontal" }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <% if is_new %>
    <%= form_file_field f, :path, '画像' %>
  <% else %>
    <%= link_to image_tag(image.path.thumb.url), image.path.url if image.path.thumb.url.present? %>
  <% end %>
  <%= form_number_field f, :fav_count, 'いいね数' %>
  <%= form_submit f, submit_label %>
<% end %>

web/app/views/images/edit.html.erb
<% provide(:title, '画像編集') %>
<h2><%= yield(:title) %></h2>

<p>素材画像の情報を編集します。</p>

<%= render partial: 'form',
           locals: { form_for_url: image_path(@image), image: @image, submit_label: '更新する', is_new: false } %>

web/app/views/images/index.html.erb
<% provide(:title, '画像一覧') %>
<h2><%= yield(:title)%></h2>
<p>
  現在登録されている画像の一覧です。
</p>
<% @images.each do |image| %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <b>HSV = (<%= image.mean_h.round(2) %>, <%= image.mean_s.round(2) %>, <%= image.mean_v.round(2) %>)</b>
    </div>
    <div class="panel-body">
      <%= link_to image_tag(image.path.thumb.url), image.path.url if image.path.thumb.url.present? %>
      <div align="center">
        いいねの数: <%= image.fav_count %>
      </div>
    </div>
    <div class="panel-footer">
      <div class="btn-group btn-group-justified">
        <%= link_to "編集", edit_image_path(image), class: 'btn btn-success' %>
        <%= link_to "削除", image, method: :delete, class: 'btn btn-danger',
                    data: { confirm: image[:path] + 'を本当に削除しますか？' } %>
      </div>
    </div>
  </div>
<% end %>

web/app/views/images/new.html.erb
<% provide(:title, '画像登録') %>
<h2><%= yield(:title) %></h2>

<p>素材画像を登録します。</p>

<%= render partial: 'form',
           locals: { form_for_url: images_path, image: @image, submit_label: '登録する', is_new: true } %>

web/app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mosaic", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "画像一覧", images_path %></li>
        <li><%= link_to "画像登録", new_image_path %></li>
      </ul>
    </div>
  </div>
</div>

web/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> - Mosaic Art Generator</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',  'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

web/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= "#{object.errors.count}個のエラーがあります。" %>
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

web/app/views/static_pages/home.html.erb
<% provide(:title, 'ホーム') %>
<h2>Mosaic Art Generator</h2>

<p>現在完成しているモザイクアート</p>

<%= image_tag('/output.jpg') %>

<p>現在登録されている画像の数: <%= @images_num %></p>

<p>メニューから素材画像を登録してください。</p>

<br>
<% if @log.size == 0 || @log[@log.size - 1].chomp == 'end' %>
  <h2>モザイクアート生成器</h2>
  <%= form_for(@target, url: static_pages_create_path, html: { class: "form-horizontal" }) do |f| %>
    <%= form_file_field f, :path, '目標画像' %>
    <%= form_submit f, 'モザイクアートを生成する' %>
  <% end %>
<% else %>
  <h2>モザイクアート生成ログ</h2>
  <p>
    <% @log.each do |l| %>
      <%= simple_format(l) %>
    <% end %>
  </p>
<% end %>